# Generated by Django 4.1.6 on 2023-02-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='usr',
        ),
        migrations.AddField(
            model_name='publisher',
            name='name',
            field=models.CharField(default='roni', max_length=100),
            preserve_default=False,
        ),
    ]
