# Generated by Django 4.1.6 on 2023-02-21 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0010_alter_broadcastintv_broadcast'),
        ('core', '0002_remove_publisher_usr_publisher_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TvOpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], verbose_name='Weekday')),
                ('from_hour', models.TimeField(verbose_name='Opening')),
                ('to_hour', models.TimeField(verbose_name='Closing')),
                ('tv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='tv.tv')),
            ],
            options={
                'verbose_name': 'Opening Hours',
                'verbose_name_plural': 'Opening Hours',
                'ordering': ['tv', 'weekday', 'from_hour'],
            },
        ),
    ]
