# Generated by Django 4.1.6 on 2023-02-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tvopeninghours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvopeninghours',
            name='weekday',
            field=models.IntegerField(choices=[(1, 'Sunday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday'), (7, 'Saturday')], verbose_name='Weekday'),
        ),
    ]
