# Generated by Django 4.1.6 on 2023-02-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_publishertype"),
    ]

    operations = [
        migrations.AddField(
            model_name="publisher", name="about", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="publisher",
            name="contact_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Contact name"
            ),
        ),
        migrations.AddField(
            model_name="publisher",
            name="contact_phone",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Contact phone"
            ),
        ),
        migrations.AddField(
            model_name="publisher",
            name="email",
            field=models.CharField(blank=True, max_length=100, verbose_name="Email"),
        ),
        migrations.AddField(
            model_name="publisher",
            name="geojson",
            field=models.JSONField(blank=True, default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="publisher",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="publishers-logos/"
            ),
        ),
        migrations.AddField(
            model_name="publisher",
            name="phone",
            field=models.CharField(blank=True, max_length=100, verbose_name="Phone"),
        ),
        migrations.AddField(
            model_name="publisher",
            name="publishers_types",
            field=models.ManyToManyField(
                blank=True,
                related_name="publishers",
                to="core.publishertype",
                verbose_name="publishers types",
            ),
        ),
        migrations.AddField(
            model_name="publisher",
            name="qr_link",
            field=models.CharField(blank=True, max_length=100, verbose_name="QR link"),
        ),
    ]
