# Generated by Django 4.1.6 on 2023-02-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_publisher_about_publisher_contact_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="publisher",
            name="address",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
