# Generated by Django 4.1.6 on 2023-02-27 08:19

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_publisher_geojson"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publisher",
            name="geojson",
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
