# Generated by Django 4.1.6 on 2023-03-03 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0022_advertisingagency'),
        ('core', '0009_alter_publisher_geojson'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='adv_agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publishers', to='tv.advertisingagency'),
        ),
    ]
