# Generated by Django 3.2.18 on 2023-03-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_publisher_adv_agency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='contact_name',
            field=models.CharField(blank=True, default='איש קשר חסר', max_length=100, verbose_name='Contact name'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='contact_phone',
            field=models.CharField(blank=True, default='0', max_length=100, verbose_name='Contact phone'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='email',
            field=models.CharField(blank=True, default='A@A.com', max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='phone',
            field=models.CharField(blank=True, default='0', max_length=100, verbose_name='Phone'),
        ),
    ]
