# Generated by Django 3.2.18 on 2023-03-23 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0029_broadcast_deleted'),
        ('core', '0011_auto_20230321_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='broadcasts',
        ),
        migrations.AddField(
            model_name='publisher',
            name='broadcasts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publisher', to='tv.broadcast'),
        ),
    ]
