# Generated by Django 3.2.18 on 2023-03-23 15:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_publisher_broadcasts'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publisher',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
