# Generated by Django 4.0 on 2023-03-25 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20230323_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='publishers_types',
            field=models.ManyToManyField(blank=True, related_name='publishers', to='core.PublisherType', verbose_name='publishers types'),
        ),
    ]
