# Generated by Django 4.0.1 on 2023-02-14 14:15

from django.db import migrations, models
import pi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PiDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('remote_last_image', models.ImageField(upload_to=pi.models.image_path)),
                ('remote_last_image_updated', models.DateTimeField(null=True)),
                ('socket_status_updated', models.DateTimeField(null=True)),
                ('cec_hdmi_status', models.CharField(default='unknown', max_length=100)),
            ],
        ),
    ]
