# Generated by Django 4.0.1 on 2023-02-15 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenSocketConnections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=100, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pi.pidevice', unique=True)),
            ],
        ),
    ]
