# Generated by Django 4.0.1 on 2023-02-15 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pi', '0002_opensocketconnections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opensocketconnections',
            name='id',
        ),
        migrations.AlterField(
            model_name='opensocketconnections',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pi.pidevice'),
        ),
    ]
