# Generated by Django 4.0.1 on 2023-02-15 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pi', '0003_remove_opensocketconnections_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opensocketconnections',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='open_socket_connection', serialize=False, to='pi.pidevice'),
        ),
    ]
