# Generated by Django 4.0.1 on 2023-02-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi', '0004_alter_opensocketconnections_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='pidevice',
            name='group_channel_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='OpenSocketConnections',
        ),
    ]
