# Generated by Django 4.1.5 on 2023-02-18 09:05

from django.db import migrations, models
import pi.models


class Migration(migrations.Migration):

    dependencies = [
        ("pi", "0005_pidevice_group_channel_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pidevice",
            name="remote_last_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=pi.models.image_path
            ),
        ),
    ]
