# Generated by Django 4.1.6 on 2023-03-07 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi', '0006_alter_pidevice_remote_last_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pidevice',
            name='group_channel_name',
        ),
        migrations.RemoveField(
            model_name='pidevice',
            name='remote_last_image_updated',
        ),
        migrations.AddField(
            model_name='pidevice',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
