# Generated by Django 4.1.6 on 2023-03-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi', '0007_remove_pidevice_group_channel_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pidevice',
            name='image_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
