# Generated by Django 4.1.7 on 2023-03-08 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi', '0008_pidevice_image_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='pidevice',
            name='telegram_connection_error_sent',
            field=models.BooleanField(default=False),
        ),
    ]
