# Generated by Django 3.2.18 on 2023-03-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi', '0009_pidevice_telegram_connection_error_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pidevice',
            name='image_updated',
        ),
        migrations.AddField(
            model_name='pidevice',
            name='group_channel_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
