# Generated by Django 3.2.18 on 2023-03-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi', '0010_auto_20230313_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='pidevice',
            name='image_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
