# Generated by Django 4.0 on 2023-05-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi', '0011_pidevice_image_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pidevice',
            name='cec_hdmi_status',
            field=models.TextField(default='unknown'),
        ),
    ]
