# Generated by Django 4.0 on 2023-03-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0016_openinghours'),
        ('tv', '0032_broadcastintv_enable_countdown'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_off_all_tvs', models.BooleanField(default=False)),
                ('defult_broadcasts', models.ManyToManyField(blank=True, to='tv.Broadcast')),
                ('defult_opening_hours', models.ManyToManyField(blank=True, to='core.OpeningHours')),
            ],
        ),
    ]
