# Generated by Django 4.0 on 2023-03-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalSettings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalsettings',
            options={'ordering': ['order', '-id']},
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
