# Generated by Django 4.1.5 on 2023-02-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tv", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="broadcast",
            name="media_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
