# Generated by Django 4.0.1 on 2023-02-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0002_broadcast_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tv',
            name='broadcasts',
            field=models.ManyToManyField(blank=True, related_name='tv', through='tv.BroadcastInTv', to='tv.Broadcast'),
        ),
    ]
