# Generated by Django 4.0.1 on 2023-02-14 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pi', '0001_initial'),
        ('tv', '0003_alter_tv_broadcasts'),
    ]

    operations = [
        migrations.AddField(
            model_name='tv',
            name='pi',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tv', to='pi.pidevice'),
        ),
    ]
