# Generated by Django 4.0.1 on 2023-02-20 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0004_tv_pi'),
    ]

    operations = [
        migrations.CreateModel(
            name='playedBroadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tv.broadcast')),
                ('tv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tv.tv')),
            ],
        ),
    ]
