# Generated by Django 4.0.1 on 2023-02-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0005_playedbroadcast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playedbroadcast',
            name='uuid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
