# Generated by Django 4.1.6 on 2023-02-20 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tv", "0006_alter_playedbroadcast_uuid"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="playedbroadcast", options={"ordering": ["-time"]},
        ),
        migrations.AlterUniqueTogether(
            name="playedbroadcast",
            unique_together={("uuid", "tv", "broadcast", "time")},
        ),
    ]
