# Generated by Django 4.1.6 on 2023-02-21 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0008_broadcast_usr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broadcast',
            name='usr',
        ),
    ]
