# Generated by Django 4.1.6 on 2023-02-21 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0009_remove_broadcast_usr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcastintv',
            name='broadcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_in_tv', to='tv.broadcast'),
        ),
    ]
