# Generated by Django 4.1.6 on 2023-02-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tv", "0010_alter_broadcastintv_broadcast"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="broadcast", options={"ordering": ["-created"]},
        ),
        migrations.AddField(
            model_name="broadcastintv",
            name="plays_left",
            field=models.IntegerField(default=0),
        ),
    ]
