# Generated by Django 4.1.6 on 2023-02-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tv", "0011_alter_broadcast_options_broadcastintv_plays_left"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ContentWithHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "content_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="broadcastintv", options={"ordering": ["order", "-created"]},
        ),
        migrations.AddField(
            model_name="tv",
            name="address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="tv",
            name="contact_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Contact name"
            ),
        ),
        migrations.AddField(
            model_name="tv",
            name="contact_phone",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Contact phone"
            ),
        ),
        migrations.AddField(
            model_name="tv",
            name="email",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Email"
            ),
        ),
        migrations.AddField(
            model_name="tv",
            name="location",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tv",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="tv-logos/"),
        ),
        migrations.AddField(
            model_name="tv",
            name="phone",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Phone"
            ),
        ),
        migrations.AddField(
            model_name="tv",
            name="buisness_type",
            field=models.ManyToManyField(
                blank=True, related_name="tvs", to="tv.businesstype"
            ),
        ),
        migrations.AddField(
            model_name="tv",
            name="not_to_show_list",
            field=models.ManyToManyField(
                blank=True, related_name="not_to_show_list", to="tv.contentwithhistory"
            ),
        ),
        migrations.AddField(
            model_name="tv",
            name="yes_to_show_list",
            field=models.ManyToManyField(
                blank=True, related_name="yes_to_show_list", to="tv.contentwithhistory"
            ),
        ),
    ]
