# Generated by Django 4.1.6 on 2023-02-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tv", "0012_businesstype_contentwithhistory_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tv",
            name="address",
            field=models.CharField(blank=True, default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tv",
            name="buisness_type",
            field=models.ManyToManyField(
                blank=True,
                related_name="tvs",
                to="tv.businesstype",
                verbose_name="Business type",
            ),
        ),
        migrations.AlterField(
            model_name="tv",
            name="contact_name",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Contact name"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tv",
            name="contact_phone",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Contact phone"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tv",
            name="email",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Email"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tv",
            name="phone",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Phone"
            ),
            preserve_default=False,
        ),
    ]
