# Generated by Django 4.1.6 on 2023-02-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tv", "0013_alter_tv_address_alter_tv_buisness_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tv",
            name="qr_link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
