# Generated by Django 4.1.6 on 2023-02-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tv", "0014_tv_qr_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tv",
            name="qr_link",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
    ]
