# Generated by Django 4.1.6 on 2023-02-23 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tv", "0015_alter_tv_qr_link"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tv", old_name="buisness_type", new_name="buisness_types",
        ),
    ]
