# Generated by Django 4.1.6 on 2023-02-23 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tv", "0016_rename_buisness_type_tv_buisness_types"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contentwithhistory", options={"ordering": ["-created"]},
        ),
        migrations.RenameField(
            model_name="tv", old_name="qr_link", new_name="web_link",
        ),
    ]
