# Generated by Django 4.1.6 on 2023-02-28 05:46

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0017_alter_contentwithhistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='qr_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tv',
            name='location',
            field=jsonfield.fields.JSONField(default={}, max_length=200),
            preserve_default=False,
        ),
    ]
