# Generated by Django 4.1.6 on 2023-03-01 10:06

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("tv", "0017_alter_contentwithhistory_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tv",
            name="manual_turn_off",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="tv",
            name="location",
            field=jsonfield.fields.JSONField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
