# Generated by Django 4.1.6 on 2023-02-27 13:34

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0017_alter_contentwithhistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tv',
            name='location',
            field=jsonfield.fields.JSONField(max_length=200),
        ),
    ]
