# Generated by Django 4.1.6 on 2023-03-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tv", "0018_tv_manual_turn_off_alter_tv_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="playedbroadcast",
            name="uri_key",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="tv",
            name="uri_key",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
