# Generated by Django 4.1.6 on 2023-02-28 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0018_broadcast_qr_link_alter_tv_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='qr_link',
            field=models.CharField(blank=True, default=123, max_length=100),
            preserve_default=False,
        ),
    ]
