# Generated by Django 4.1.6 on 2023-03-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tv", "0019_playedbroadcast_uri_key_tv_uri_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="playedbroadcast",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
