# Generated by Django 4.1.6 on 2023-03-02 06:03

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("tv", "0020_playedbroadcast_is_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tv",
            name="location",
            field=jsonfield.fields.JSONField(blank=True, max_length=200, null=True),
        ),
    ]
