# Generated by Django 4.1.6 on 2023-03-03 00:47

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0021_alter_tv_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisingAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('geojson', jsonfield.fields.JSONField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='Phone')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='Email')),
                ('contact_name', models.CharField(blank=True, max_length=100, verbose_name='Contact name')),
                ('contact_phone', models.CharField(blank=True, max_length=100, verbose_name='Contact phone')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='advertising-agencies-logos/')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
