# Generated by Django 4.1.6 on 2023-03-03 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0022_advertisingagency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisingagency',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='adv-agens-logos/'),
        ),
    ]
