# Generated by Django 4.1.6 on 2023-03-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0023_alter_advertisingagency_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastintv',
            name='telegram_notification_in',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='broadcastintv',
            name='telegram_notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
