# Generated by Django 4.1.7 on 2023-03-10 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0024_broadcastintv_telegram_notification_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastintv',
            name='master',
            field=models.BooleanField(default=False),
        ),
    ]
