# Generated by Django 4.1.7 on 2023-03-12 03:16

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0025_broadcastintv_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='history',
            field=jsonfield.fields.JSONField(blank=True, default=list, null=True),
        ),
    ]
