# Generated by Django 3.2.18 on 2023-03-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0026_broadcast_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tv',
            options={'ordering': ['created']},
        ),
        migrations.AlterField(
            model_name='tv',
            name='contact_name',
            field=models.CharField(blank=True, default='-', max_length=100, verbose_name='Contact name'),
        ),
        migrations.AlterField(
            model_name='tv',
            name='contact_phone',
            field=models.CharField(blank=True, default='0', max_length=100, verbose_name='Contact phone'),
        ),
        migrations.AlterField(
            model_name='tv',
            name='email',
            field=models.CharField(blank=True, default='A@A.com', max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='tv',
            name='phone',
            field=models.CharField(blank=True, default='0', max_length=100, verbose_name='Phone'),
        ),
    ]
