# Generated by Django 3.2.18 on 2023-03-21 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0027_auto_20230321_1508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tv',
            options={'ordering': ['-created']},
        ),
    ]
