# Generated by Django 3.2.18 on 2023-03-23 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_publisher_broadcasts'),
        ('tv', '0029_broadcast_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to='core.publisher'),
        ),
    ]
