# Generated by Django 4.0 on 2023-03-25 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0030_broadcast_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tv',
            name='buisness_types',
            field=models.ManyToManyField(blank=True, related_name='tvs', to='tv.BusinessType', verbose_name='Business type'),
        ),
        migrations.AlterField(
            model_name='tv',
            name='not_to_show_list',
            field=models.ManyToManyField(blank=True, related_name='not_to_show_list', to='tv.ContentWithHistory'),
        ),
        migrations.AlterField(
            model_name='tv',
            name='yes_to_show_list',
            field=models.ManyToManyField(blank=True, related_name='yes_to_show_list', to='tv.ContentWithHistory'),
        ),
    ]
