# Generated by Django 3.2.18 on 2023-03-27 13:44

from django.db import migrations, models

def init_order(apps, schema_editor):
    Tv = apps.get_model('tv', 'Tv')
    for i, tv in enumerate(Tv.objects.all()):
        tv.order = i * 10
        tv.save()

class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0032_broadcastintv_enable_countdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='tv',
            name='order',
            field=models.IntegerField(default=0),
        ),
        # init order
        migrations.RunPython(init_order, migrations.RunPython.noop),
    ]
