# Generated by Django 3.2.18 on 2023-03-27 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0033_tv_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tv',
            options={'ordering': ['-order', '-created']},
        ),
    ]
