# Generated by Django 4.0 on 2023-04-13 22:18

from django.db import migrations
def forward_tvs(apps, schema_editor):
    broadcast_in_tv = apps.get_model('tv', 'BroadcastInTv')
    broadcast_in_tvs = apps.get_model('tv', 'BroadcastInTvs')

    for obj in broadcast_in_tv.objects.all():
        # create new broadcast_in_tvs with 1 tv (it's own) and copy all the other data
        new_b_in_tvs = broadcast_in_tvs.objects.create(
            broadcast=obj.broadcast,
            updated=obj.updated,
            created=obj.created,
            duration=obj.duration,
            order=obj.order,
            master=obj.master,)
        new_b_in_tvs.tvs.add(obj.tv)
        new_b_in_tvs.save()
class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0035_broadcastintvsschedule_betweendateschedule_and_more'),
    ]

    operations = [
        migrations.RunPython(forward_tvs, migrations.RunPython.noop),
    ]
