# Generated by Django 4.0 on 2023-04-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0036_forward_tvs'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastintvsschedule',
            name='is_active_var',
            field=models.BooleanField(default=False),
        ),
    ]
