# Generated by Django 4.0 on 2023-04-23 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0037_broadcastintvsschedule_is_active_var'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broadcastintvs',
            options={'ordering': ['order', '-created']},
        ),
    ]
