# Generated by Django 4.0 on 2023-04-30 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0038_alter_broadcastintvs_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playedbroadcast',
            name='broadcast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tv.broadcast'),
        ),
        migrations.AlterField(
            model_name='playedbroadcast',
            name='tv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tv.tv'),
        ),
    ]
