# Generated by Django 4.0 on 2023-05-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0039_alter_playedbroadcast_broadcast_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playedbroadcast',
            name='uuid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
