# Generated by Django 4.0 on 2023-07-31 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0041_asset_priceingplen_spot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='file',
            new_name='media',
        ),
        migrations.AddField(
            model_name='asset',
            name='media_type',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
