# Generated by Django 4.0 on 2023-07-31 09:41

from django.db import migrations

def pass_noop(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0042_rename_file_asset_media_asset_media_type'),
    ]

    operations = [
        migrations.RunPython(pass_noop, reverse_code=migrations.RunPython.noop),
    ]
