# Generated by Django 4.0 on 2023-08-06 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0043_auto_20230731_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultTvFotter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='default-tv-fotter/')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('index_in_tv', models.IntegerField(default=0, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TvFotter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tv-fotter/')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('index_in_tv', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AlterField(
            model_name='spot',
            name='tvs',
            field=models.ManyToManyField(blank=True, related_name='spots', to='tv.Tv'),
        ),
        migrations.AddField(
            model_name='tv',
            name='fotter_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotter_1', to='tv.tvfotter'),
        ),
        migrations.AddField(
            model_name='tv',
            name='fotter_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotter_2', to='tv.tvfotter'),
        ),
        migrations.AddField(
            model_name='tv',
            name='fotter_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotter_3', to='tv.tvfotter'),
        ),
        migrations.AddField(
            model_name='tv',
            name='fotter_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotter_4', to='tv.tvfotter'),
        ),
    ]
