# Generated by Django 4.0 on 2023-08-06 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0044_defaulttvfotter_tvfotter_alter_spot_tvs_tv_fotter_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvfotter',
            name='index_in_tv',
        ),
    ]
