# Generated by Django 4.0 on 2023-08-06 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0045_remove_tvfotter_index_in_tv'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tvfotter',
            options={'ordering': ['-created', 'tv', 'location_default']},
        ),
        migrations.RemoveField(
            model_name='tv',
            name='fotter_1',
        ),
        migrations.RemoveField(
            model_name='tv',
            name='fotter_2',
        ),
        migrations.RemoveField(
            model_name='tv',
            name='fotter_3',
        ),
        migrations.RemoveField(
            model_name='tv',
            name='fotter_4',
        ),
        migrations.AddField(
            model_name='defaulttvfotter',
            name='location_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tvfotter',
            name='location_default',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='fotter', to='tv.defaulttvfotter'),
        ),
        migrations.AddField(
            model_name='tvfotter',
            name='tv',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='tv_fotter', to='tv.tv'),
        ),
        migrations.AlterUniqueTogether(
            name='tvfotter',
            unique_together={('tv', 'location_default')},
        ),
    ]
