# Generated by Django 4.0 on 2023-08-07 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_openinghours'),
        ('tv', '0047_auto_20230807_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='publisher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.publisher'),
            preserve_default=False,
        ),
    ]
