# Generated by Django 4.0 on 2023-08-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0048_alter_spot_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
